services:
  - type: web
    name: Volt-API
    env: node
    rootDir: Backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
