local DarkTheme = {
    MainBackground = Color3.new(0.075, 0.075, 0.075),
    SecondaryBackground = Color3.new(0.094, 0.094, 0.094),
    TertiaryBackground = Color3.new(0.11, 0.11, 0.11),
    
    StrokeColor = Color3.new(0.216, 0.216, 0.216),
    ActiveStrokeColor = Color3.new(1, 1, 1),
    
    TextPrimary = Color3.new(1, 1, 1),
    TextSecondary = Color3.new(0.6, 0.6, 0.6),
    TextTertiary = Color3.new(0.478, 0.478, 0.478),
    
    DangerBackground = Color3.fromRGB(36, 24, 24),
    DangerHover = Color3.fromRGB(48, 28, 28),
    DangerStroke = Color3.fromRGB(180, 50, 50),
    DangerText = Color3.fromRGB(240, 120, 120),
    
    IconColor = Color3.new(1, 1, 1)
}

return DarkTheme
