local DarkTheme = {
    MainBackground = Color3.new(0.075, 0.075, 0.075),
    SecondaryBackground = Color3.new(0.11, 0.11, 0.11),
    TertiaryBackground = Color3.new(0.094, 0.094, 0.094),
    
    StrokeColor = Color3.new(0.216, 0.216, 0.216),
    HighlightStrokeColor = Color3.new(0.353, 0.353, 0.353),
    
    TextPrimary = Color3.new(0.537, 0.537, 0.537),
    TextSecondary = Color3.new(0.478, 0.478, 0.478),
    
    IconColor = Color3.new(1, 1, 1)
}

return DarkTheme
