local DraculaTheme = {
    MainBackground = Color3.fromRGB(40, 42, 54),
    SecondaryBackground = Color3.fromRGB(45, 47, 60),
    TertiaryBackground = Color3.fromRGB(50, 52, 65),
    
    StrokeColor = Color3.fromRGB(68, 71, 90),
    ActiveStrokeColor = Color3.fromRGB(189, 147, 249),
    
    TextPrimary = Color3.fromRGB(248, 248, 242),
    TextSecondary = Color3.fromRGB(139, 233, 253),
    TextTertiary = Color3.fromRGB(98, 114, 164),
    
    DangerBackground = Color3.fromRGB(255, 85, 85),
    DangerHover = Color3.fromRGB(255, 105, 105),
    DangerStroke = Color3.fromRGB(255, 125, 125),
    DangerText = Color3.fromRGB(80, 20, 20),
    
    IconColor = Color3.fromRGB(80, 250, 123)
}

return DraculaTheme
