local LightTheme = {
    MainBackground = Color3.fromRGB(240, 240, 245),
    SecondaryBackground = Color3.fromRGB(255, 255, 255),
    TertiaryBackground = Color3.fromRGB(230, 230, 235),
    
    StrokeColor = Color3.fromRGB(150, 150, 150),
    ActiveStrokeColor = Color3.fromRGB(80, 80, 80),
    
    TextPrimary = Color3.fromRGB(30, 30, 35),
    TextSecondary = Color3.fromRGB(100, 100, 105),
    TextTertiary = Color3.fromRGB(130, 130, 135),
    
    DangerBackground = Color3.fromRGB(255, 220, 220),
    DangerHover = Color3.fromRGB(255, 200, 200),
    DangerStroke = Color3.fromRGB(200, 80, 80),
    DangerText = Color3.fromRGB(200, 50, 50),
    
    IconColor = Color3.fromRGB(50, 50, 50)
}

return LightTheme
