local SolarizedTheme = {
    MainBackground = Color3.fromRGB(0, 43, 54),
    SecondaryBackground = Color3.fromRGB(7, 54, 66),
    TertiaryBackground = Color3.fromRGB(14, 65, 78),
    
    StrokeColor = Color3.fromRGB(88, 110, 117),
    ActiveStrokeColor = Color3.fromRGB(38, 139, 210),
    
    TextPrimary = Color3.fromRGB(253, 246, 227),
    TextSecondary = Color3.fromRGB(147, 161, 161),
    TextTertiary = Color3.fromRGB(131, 148, 150),
    
    DangerBackground = Color3.fromRGB(220, 50, 47),
    DangerHover = Color3.fromRGB(240, 60, 50),
    DangerStroke = Color3.fromRGB(255, 80, 70),
    DangerText = Color3.fromRGB(253, 246, 227),
    
    IconColor = Color3.fromRGB(133, 153, 0)
}

return SolarizedTheme
