local VoidTheme = {
    MainBackground = Color3.fromRGB(0, 0, 0),
    SecondaryBackground = Color3.fromRGB(5, 5, 5),
    TertiaryBackground = Color3.fromRGB(10, 10, 10),
    
    StrokeColor = Color3.fromRGB(25, 25, 25),
    ActiveStrokeColor = Color3.fromRGB(255, 255, 255),
    
    TextPrimary = Color3.fromRGB(255, 255, 255),
    TextSecondary = Color3.fromRGB(160, 160, 160),
    TextTertiary = Color3.fromRGB(100, 100, 100),
    
    DangerBackground = Color3.fromRGB(25, 5, 5),
    DangerHover = Color3.fromRGB(40, 10, 10),
    DangerStroke = Color3.fromRGB(150, 20, 20),
    DangerText = Color3.fromRGB(255, 80, 80),
    
    IconColor = Color3.fromRGB(255, 255, 255)
}

return VoidTheme
